#pragma once

#include <iostream>
#include <vector>
#include <memory>
#include <type_traits>
#include <tuple>
#include <chrono>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <functional>
#include <map>
#include <unordered_map>
#include <optional>
#include <unordered_set>
#include <set>
#include <limits>
#include <cstring>
#include <cstdlib>
#include <ctime>
